#!/usr/bin/env bash

# Author: RilCritch

# Last update: 07/07/23

# Description: script that runs fzf on files and opens kitty on specified dir

# get directory
choice=$(find $HOME -type d | fzf --header-first --reverse --color=16 --prompt='▶ ' --pointer='󱦰' --preview 'exa --tree -la --icons -F -L=2 --group-directories-first --no-filesize --no-user --time-style='long-iso' {}')

if [ -n "$choice" ]; then
    # setsid kitty -d $choice
    qtile cmd-obj -o cmd -f spawn -a "kitty -d $choice"
fi
