#!/usr/bin/env bash
#
# DescriptionSimple script that uses Qtiles command line interface to print out keybindings -- need to improve output
# 
# Dependencies: cmdrunandwait, clr, lineacross
#
# author: RilCritch

qtilecmd="qtile cmd-obj -o cmd -f display_kb"
pythonform="python -c 'import sys; print(eval(sys.stdin.read()))'"

printkeys="$qtilecmd | $pythonform | cut -d ' '  -f2- | sed 's/^[[:space:]]*//'"

$HOME/mydots/scripts/cmdrunandwait "$printkeys"
